R/RNetCDF.R
Simple stop catch for empty string "" to `open.nc` or `create.nc`. 
Fixes #18 
```R
library(RNetCDF)
#a <- open.nc("")
#a <- create.nc("")
```
=> fix for empty source string

man/utcal.nc.Rd
=> Use NC_DOUBLE to avoid misleading users of utcal.nc

DESCRIPTION, man/att.get.nc.Rd, man/var.get.nc.Rd, src/attribute.c, src/convert.c, src/convert.h, src/variable.c, tests/RNetCDF-test.R
Package bit64 provides type `integer64`, which is a space-efficient and flexible way to represent large integers. Various conversions and numeric operations (as signed 64-bit integers) are supported by `integer64` within R. This PR adds support for `integer64` in RNetCDF while dropping support for large integers expressed as character vectors.
=> Allow reading and writing of bit64 integers

R/RNetCDF.R, man/type.inq.nc.Rd, src/RNetCDF.h, src/attribute.c, src/common.c, src/common.h, src/init.c, src/type.c, src/variable.c, tests/RNetCDF-test.R
Add function `type.inq.nc` to get details of user-defined types, including the defined values of enumerated types and components of compound types.
=> Support inquiries about user-defined types

src/convert.c
`gctorture` showed that R objects can be garbage collected in the interval between defining them and assigning them to a (protected) environment.
The solution involved adding `PROTECT`/`UNPROTECT` statements around the definition and assignment steps. We use these statements directly because the protection only needs to be temporary. If we used `R_nc_protect`, the protection would last until `RRETURN`, and we could overflow the protection stack if the number of assigned variables was large.
We may have gone too far by adding `PROTECT`ion where it is not needed, but better safe than sorry.
=> PROTECT values before assignment to hashed environment

src/convert.c
Valgrind revealed an attempt to access past the end of an array during conversion from vlen arrays of NC_CHAR to R strings. The RNetCDF C code was writing a temporary null character into the C buffer before passing each string to R. The last null character was written outside the bounds of the C buffer.
An obvious solution was to extend the size of the C buffer by 1 byte. However, this does not work for vlen arrays, where memory is managed by the netcdf4/hdf5 library and is therefore outside our control.
An alternative solution is to use `mkCharLen` when passing strings to R. This allows the length of the string to be specified without adding a null character. The string created by R always contains the specified number of bytes, possibly including null characters and random bytes. If a …
=> Ensure that strings are properly terminated without altering values

R/RNetCDF.R, src/attribute.c, src/common.c, src/common.h, src/convert.c, src/convert.h, src/dataset.c, src/dimension.c, src/group.c, src/type.c, src/udunits.c, src/variable.c
Closes #42 
Extra argument checks have been added to C functions called by R. These should avoid unexpected behaviour caused by incorrect data types, out-of-range type conversions or missing values.
=> Check function arguments in C

configure, configure.ac
Resolves #48 .
Installation of RNetCDF from source code was failing in the R for Mac GUI. The netcdf library was installed as part of Fink, but similar problems would probably occur with other package managers or custom installations.
The causes of the problem were found to be:
1. R for Mac GUI starts with a minimal PATH, so that `nc-config` is not found. This can be fixed by using `Sys.setenv` to modify PATH inside an R session, or by launching the R GUI from a terminal after defining PATH as required.
2. The `configure` script was not adding preprocessor flags from `nc-config` to CPPFLAGS, so the compiler was not searching for header files in the correct directories.
Item 1 may only be a problem on Mac, and it is not caused by RNetCDF itself. 
This PR fixes item 2, which could affect …
=> Find netcdf header files in non-standard locations 

R/RNetCDF.R, man/print.nc.Rd, src/attribute.c, src/convert.c, tests/RNetCDF-test.R
Resolves #37 .
`print.nc` now shows definitions of user-defined types, and it also reports the existence of user-defined attributes and variables. Values of user-defined attributes can be very complicated, so they are not shown by the current implementation. User-defined attributes can be read by `att.get.nc` if required. The information presented by `print.nc` should be enough to reveal the structure of any netcdf dataset.
Related tasks included:
* Handling scalars and vectors of user-defined type in attributes
* Expanding tests of user-defined types in attributes
* Handling class `integer64` while keeping package `bit64` an optional dependency
=> Show user defined types and attributes in print.nc

R/RNetCDF.R, man/file.inq.nc.Rd, src/dataset.c, tests/RNetCDF-test.R
Resolves #51 .
Some applications may be sensitive to the version of the NetCDF library. We expose the library version to users by adding a new element `libvers` to the output list from `file.inq.nc`.
Although the library version is not strictly a property of a NetCDF dataset, the library version is fixed while a dataset is open in RNetCDF. `file.inq.nc` reports properties of an open dataset, and it is therefore an appropriate function to report the library version.
=> Show NetCDF library version

INSTALL, R/RNetCDF.R, configure, configure.ac, man/create.nc.Rd, man/var.def.nc.Rd, man/var.get.nc.Rd, man/var.inq.nc.Rd, man/var.put.nc.Rd, src/Makevars.win, src/RNetCDF.h, src/group.c, src/init.c, src/variable.c, tests/RNetCDF-test.R
Netcdf4 provides advanced settings for variables, including chunking, deflation, endianness, checksums and user-defined filters. This PR exposes the advanced settings as optional arguments in functions `var.def.nc` and `var.inq.nc`.
Resolves #32 .
=> Advanced settings for variables in netcdf4

src/convert.c
The test infrastructure at https://builder.r-hub.io/ provides environments with UBSAN and rchk. Some minor problems were identified by these tests, including:
* Undefined behaviour in memcpy when destination is a NULL pointer
* Unprotected R objects
The problems were not detected by other tests on Linux, Windows or Mac platforms. The unprotected R objects were not revealed by gctorture with or without valgrind. However, the bugs could be triggered by future changes to the R internals.
=> Avoid errors from ubsan and rchk

R/RNetCDF.R, tests/RNetCDF-test.R
The `collapse` option of `var.get.nc` should behave the same way as the `drop` option in the R indexing operator `[`. However, some edge cases of `collapse` give unexpected results. For example, when all dimensions of an array slice have size 1, `collapse` should remove the dimensions attribute, but the original dimensions are returned instead. The expected behaviour can be enforced by implementing `collapse` with the R builtin function `drop`.
=> Collapse array dimensions with drop()

DESCRIPTION
The version number has been stuck on 2.0-1 almost since the 1.9 branch was cut. The build number is being incremented before release, to distinguish the release from development versions of the package that were installed by some brave and helpful users.
=> Release version 2.0-2

DESCRIPTION, NEWS, configure, configure.ac
udunits2 support is optional in RNetCDF-2.0. It is intended that installation of RNetCDF should not fail as a result of a missing or buggy udunits2 library or header files - udunits2 support should simply be disabled. To determine if udunits2 can be supported, extra checks can be added to the `configure` script.
=> Extra checks for udunits2

DESCRIPTION
Names of external packages are supposed to be wrapped in single quotes, within the Title and Description fields of the DESCRIPTION file.
While fixing the quotes, I took the opportunity to reword the Description, hopefully improving it in the process.
=> Quote software in DESCRIPTION

src/attribute.c, src/convert.c, src/convert.h, src/type.c, src/variable.c
Valgrind reported an invalid memory access when copying the fill value for a user-defined type. This highlighted two problems and solutions:
1. NetCDF attribute conventions do not define the expected handling of missing values for user-defined types. Rather than adopting our own convention, it is safer to let users decide for themselves and handle missing values in their own R code.
2. Missing values (and related parameters) are determined in function `R_nc_miss_att`, and they are passed to other routines as void pointers. The size of the data types is assumed by the called routines, but mismatches can easily occur. As a safety precaution, the size of the missing values (and related parameters) can be passed as an extra argument. Routines can then check that the void pointers have the …
=> Disable automatic conversion of missing values for user-defined types

src/Makevars.win
Windows platforms on https://builder.r-hub.io were unable to build RNetCDF, even using netcdf and hdf5 libraries from https://github.com/rwinlib . For unknown reasons, the local library path was being searched before user-defined library paths in the link step. This problem does not occur on https://win-builder.r-project.org.
As a solution to this problem, the static libraries from rwinlib can be linked explicitly by specifying their relative pathnames, without relying on the search path set by `-L`. The solution works on both r-hub and win-builder.
=> Fix Windows builds on r-hub

src/variable.c
Compiler warnings about unused variables are not usually harmful, but they add noise to the output that may hide other problems. It is best to avoid these warnings if possible.
Some variable declarations can be removed, as they are no longer used.
Other declarations are used in optional code blocks that are wrapped in `#ifdef` logic. These declarations can be wrapped in similar preprocessor logic, so that compiler warnings about unused variables do not occur.
=> Avoid unused variables

DESCRIPTION, src/attribute.c, src/common.c, src/common.h, src/convert.c, src/convert.h, src/dataset.c, src/dimension.c, src/group.c, src/type.c, src/udunits.c, src/variable.c
[CRAN](http://cran.r-project.org) runs [rchk](https://github.com/kalibera/rchk) on submitted packages, and RNetCDF_2.1 causes the following warning:
> Function R_nc_protect
>  [PB] has possible protection stack imbalance RNetCDF/src/common.c:49
This function wraps the `PROTECT` macro and increments a counter, which is used by the function `R_nc_unprotect` to call `UNPROTECT` at all exit points from the RNetCDF C code. According to the [rchk documentation](https://github.com/kalibera/cran-checks/blob/master/rchk/PROTECT.md), wrapping of `PROTECT`/`UNPROTECT` is discouraged.
This PR implements memory protection using the recommended caller-protects convention, relying on the R runtime to reset the protection stack after exceptions (e.g. `error`). The new implementation passes the tests in …
=> Fix warnings from rchk

DESCRIPTION, NEWS, src/dataset.c
Use conditional compilation of data64 support in RNetCDF so that build succeeds with old netcdf libraries (tested with netcdf-4.1.3).
=> Fix build failure for netcdf libraries without data64 support

src/convert.c, tools/convert.m4
This merge request adds the file tools/convert.m4, which is passed through the M4 macro processor to generate src/convert.c.
The type conversion routines in src/convert.c were previously generated using macros for the C preprocessor, but limitations of the macro syntax meant that the resulting C code was not optimised for different cases. The M4 macro language is much more flexible, and the generated C code has been optimised in various ways. For example, invariant tests have been hoisted outside loop bodies, resulting in a family of optimised loops where there was previously a generic loop.
The C code generated from the M4 macros is stored fully expanded in the repository, allowing easier analysis and debugging.
=> Generate type conversions with m4 macros

tools/release.sh
Add new script tools/release.sh to set package version in files and perform various checks, such as ensuring that generated files are up-to-date.
=> Add release script

src/Makevars.ucrt, src/Makevars.win
Hello! I maintain the rwinlib binaries.
This PR updates your package to use netcdf 4.7.3 and also prepares for the new ucrt toolchains.
I have tested this works on all versions from R 3.3 - R 4.2.
=> Windows: update to netcdf 4.7.3 + ucrt support

R/RNetCDF.R, configure, configure.ac, man/var.def.nc.Rd, man/var.inq.nc.Rd, src/common.c, src/common.h, src/convert.c, src/convert.h, src/dimension.c, src/variable.c, tests/RNetCDF-test.R, tools/convert.m4
Recent versions of NetCDF have added support for hdf5 filter plugins. The initial NetCDF filter interface supported only a single filter, but hdf5 allows more than one filter per variable, and support for multiple filters has been evolving over the NetCDF-4.7.x series. The multi-filter API seems to have stabilised in NetCDF-4.8.0.
This pull request updates RNetCDF to use the multi-filter API. This also fixes a bug in the RNetCDF tests when used with NetCDF-4.8.0, due to changes in the return status of NetCDF filter inquiry routines when no filters are defined for a variable.
Please note that this PR removes support for the NetCDF single-filter routines, because they are redundant and may be deprecated in future. If plugin filters must be used with NetCDF-4.7.x, please use RNetCDF_2.4-2.
=> Support hdf5 filters via multi-filter interface

man/var.def.nc.Rd
update the description of `deflate` argument o `var.def.nc` function. Mention that it works only in netcdf4 files
=> update help file for var.def.nc

tools/convert.m4
This PR ensure that changes in #107 are not undone if src/convert.c is regenerated from tools/convert.m4.
=> Avoid use of sprintf when generating convert.c

configure, configure.ac, src/convert.c, src/variable.c, tests/RNetCDF-test.R, tools/convert.m4
The NetCDF library honours the `_FillValue` attribute of NC_STRING variables, filling unwritten strings with the specified value. This PR adds support for fill values when na.mode=5 is set for `var.put.nc` or `var.get.nc`.
When writing R strings to an NC_STRING variable, `NA` values are replaced by the `_FillValue` string. The opposite applies when reading NC_STRING variables into R strings.
=> Support fill value conversion in NC_STRING type

src/convert.c, tests/RNetCDF-test.R, tools/convert.m4
This PR adds support for fill values in compound types when `na.mode=5` is set for `var.put.nc` or `var.get.nc`.
The `_FillValue` is required to be a single item of the compound type, which defines the fill value for each field of the type. This is how the netcdf library interprets `_FillValue` for compound types, as briefly summarised in
https://github.com/Unidata/netcdf-c/issues/1011#issuecomment-395585631 .
If a compound `_FillValue` contains an array field, RNetCDF selects a _scalar_ fill value from the first element of the array field, ignoring any different fill values that may occur in other elements of the array. This allows reuse of existing RNetCDF code for array conversions, where the same scalar fill value is applied to all elements of an array. In the (unlikely) event that …
=> Support fill value conversion in compound types

src/convert.c, tests/RNetCDF-test.R, tools/convert.m4
This PR adds support for fill values in vlen types when `na.mode=5` is set for `var.put.nc` or `var.get.nc`.
The `_FillValue` attribute is required to have the same vlen type as the variable, and it must contain only a single vlen element. The first basetype value in the vlen element is used as the fill value. This is the approach used in the netcdf library, as described in
https://github.com/Unidata/netcdf-c/issues/1011#issuecomment-395585631 .
=> Support fill value conversion in vlen types

.github/workflows/check-extra.yaml, configure, configure.ac, src/Makefile.common.in
... so that PKG variables can be defined in Makefile.common, without duplicating content of other variables.
While delving into configure.ac, we fix a few other details:
* Allow nc-config to be used on Windows if explicitly requested
* Test that nc-config allows the --static option (which is not available on early 4.x versions of NetCDF).
These changes have been rescued from #124 , which was abandoned because it broke Windows builds for R<4.2.
=> Separate PKG and R variables in configure

man/att.copy.nc.Rd, man/att.delete.nc.Rd, man/att.get.nc.Rd, man/att.inq.nc.Rd, man/att.rename.nc.Rd, man/grp.inq.nc.Rd
Resolves #102
This PR adds examples for `grp.inq.nc` showing how to access data in nested groups.
It also explains the valid range of attribute ID numbers in help files for `att.*.nc` functions. This information was obtained from the documentation of NetCDF C library function `nc_inq_attname`.
=> Improve help for accessing data in groups

tools/make-recursive.sh
This fixes building on Arch Linux.
The `R_SHARE_DIR` is not necessarily located in `${R_HOME}/share`. For example on Arch Linux, `R_HOME=/usr/lib64/R` while `R_SHARE_DIR=/usr/share/R`, so the correct path of `shlib.mk` on Arch is `/usr/share/R/make/shlib.mk`.
=> Use correct path for `shlib.mk`

.github/workflows/ubuntu-native.yaml, tools/make-recursive.sh
PR #128 provided a solution for #129 and #130 . This PR aims to generalise the solution to handle R installations where the `etc` subdirectory is outside the `$R_HOME` directory tree. Such an installation is supported by the R configure script, although it may not occur in practice.
The solution adopted here assumes that R executables are stored in `$R_HOME/bin`. This is consistent with advice in https://cran.csiro.au/doc/manuals/r-release/R-exts.html#Configure-and-cleanup . The alternative of using R from the PATH could find a different version of R than the one intended for package installation.
=> Find R subdirectories using R.home function in make-recursive.sh

.github/workflows/test-ubsan.yaml, src/convert.c, tools/convert.m4
The original code worked correctly with gcc and clang, but UBSAN tests on CRAN reported warnings after upload of RNetCDF_2.7-1.
The warning was caused in RNetCDF-test.R in section "Read character vlen", which involved converting a vlen to R character vectors. One of the vlen members was defined to have zero length, so that the corresponding C buffer was a NULL pointer. This was correctly converted to an empty string by RNetCDF, but the code used to determine string length apparently relied on non-standard behaviour of the gcc and clang compilers.
=> Fix UBSAN warning when converting empty NC_CHAR to R string

configure, configure.ac, src/convert.c, src/convert.h, tests/RNetCDF-test.R, tools/convert.m4
CRAN reports failures for RNetCDF_2.7-1 tests when the package is checked with oneAPI 2023.x compilers.
After installing R with the oneAPI compilers on RHEL8 (as described in https://cran.r-project.org/doc/manuals/r-devel/R-admin.html#Intel-compilers), my experiments with compiler flags showed that tests worked correctly with the following options in `~/.R/Makevars`:
```
CFLAGS = -O3 -no-ansi-alias -fhonor-nan-compares
```
Although it would be possible to insert these compiler flags in `configure.ac`, this PR aims to fix the underlying problems in `src/convert.c` (which is generated from `tools/convert.m4`).
=> Conversions fail with oneAPI compiler

src/common.c, src/convert.c, src/udunits.c, src/variable.c, tests/RNetCDF-test.R, tools/convert.m4
In the C code of RNetCDF, errors are signalled using function calls of the form:
```
error (nc_strerror (status));
```
In package tests with the latest R-devel, these lines cause many warnings like the following:
```
warning: format string is not a string literal (potentially insecure) [-Wformat-security]
```
This PR fixes the warnings by adding a literal format string as the first argument of `error`.
=> Fix CRAN warning about potentially insecure format string

configure.win
This fixes the package to build with an upcoming version of Rtools on Windows. Netcdf now needs also libcurl, but the configure file doesn't assume that, so the patch resorts to pkg-config. Tested also with Rtools43 and Rtools42.
=> Fix linking with an upcoming version of Rtools on Windows where netcdf needs curl.

.github/workflows/check-extra.yaml, .github/workflows/check-linux-mpi.yaml, .github/workflows/check-nc-versions.yaml, .github/workflows/check-standard.yaml, .github/workflows/test-coverage.yaml, .github/workflows/test-rchk.yaml.disabled, .github/workflows/test-ubsan.yaml, .github/workflows/ubuntu-native.yaml
Github has deprecated v3 of the artifact action, so upgrade to v4 is required. To avoid problems later, we can update the checkout and cache actions as well.
=> Update github actions from v3 to v4

R/RNetCDF.R
Closes #148
`att.get.nc()` already checks `requireNamespace("bit64")` if `inherits(attval, "integer64")` and errors if not.
So upon return from `att.get.nc()`, we know that `isNamespaceLoaded("bit64")`, and therefore that the S3 method `as.character.integer64` will dispatch correctly.
=> just use as.character() & let S3 dispatch work

src/convert.c, tools/convert.m4
R-devel warns that `Rf_findVarInFrame3` is not part of the public R API, so we replace it.
=> Avoid calls to non-API entry points in R

.github/workflows/check-linux-mpi.yaml, INSTALL, configure, configure.ac
On some systems, the compiler reported by `nc-config --cc` may not be compatible with R headers. Warnings may be issued during package installation and/or the package may not work. An example of this was reported by Prof Ripley, where the compiler reported by nc-config was ancient and R was built with a newer compiler.
The compiler from nc-config is only of interest for enabling MPI. This is unlikely to be a requirement for most RNetCDF users, so it is better to use the R compiler by default. For the rarer installations that require parallel I/O, the following methods are provided:
* Specify an MPI compiler via configure option `--with-cc`. (This compiler must be compatible with R headers and provide the same MPI libraries as used by NetCDF).
* Disable nc-config and pkg-config via …
=> Do not use nc-config compiler by default

tests/RNetCDF-test.R
The `--as-cran` option of `R CMD check` reports an error when RNetCDF tests call `Rscript` without its full pathname. This occurs when testing parallel I/O with Rmpi or pbdMPI packages.
=> Call Rscript with full pathname in tests

configure, configure.ac, src/convert.c, tools/convert.m4
Recent R versions have added new API functions to replace internal functions that will become private in future R releases. This PR tests for `R_NewEnv` and `R_getVarEx` in configure, and uses them as replacements for legacy code.
=> Use new R API functions for environments

src/dataset.c, tests/RNetCDF-test.R
Occasional crashes have occurred after interrupting functions that opened netcdf files and then opening or editing the same files again. Repeatable cases have been elusive, but the cause may involve garbage collection of stale netcdf file handles. If the stale handles point to files being modified by new handles, the garbage collection will close the stale file handles, possibly corrupting the new files and causing a crash. This PR introduces a possible solution, which is to call the garbage collector before opening new file handles. This should not cause problems, other than potential slowdowns when opening many files in rapid succession (probably a rare use case).
Tests of file closures and their interactions with garbage collection are also improved in this PR.
=> Close stale file handles before opening new files

configure, configure.ac, src/config.h.in, src/convert.c, tools/convert.m4
Tests of new R API functions appeared to work in #159, but in fact, the functions were not detected even in the latest R version. This was because `R CMD config CPPFLAGS` does not set the include path for R headers. A separate command `R CMD config --cppflags` is provided for that purpose.
**Update**: Although the above approach worked, a simpler approach was taken, based on selecting R API features via the R version.
=> Fix R API feature checks
